import type {Metadata} from "next";
import "./globals.css";
import React from "react";
import Sidebar from "@/app/components/Sidebar";
import Header from "@/app/components/Header";

export const metadata: Metadata = {
    title: "HiQaody",
    description: "Generated by create next app",
};
export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" className="h-full">
        <body className="dark:text-white bg-gray-50 dark:bg-gray-900 h-full overflow-hidden">
        <div className="flex h-screen">
            {/* Sidebar - rétractable sur petit écran */}
            <aside className="lg:w-64 flex-shrink-0">
                <Sidebar/>
            </aside>

            {/* Main Content Wrapper - fixed height, non-scrollable */}
            <main className="flex-grow flex flex-col h-screen overflow-auto">
                {/* Header - fixed position */}
                <div className="flex-shrink-0 px-4 sm:px-8 md:px-16 lg:px-[6%] py-2 lg:py-0">
                    <Header title="" text=""/>
                </div>

                {/* Zone de contenu scrollable avec padding pour éviter les chevauchements */}
                <div className="flex-grow overflow-auto px-4 sm:px-8 md:px-16 lg:px-[6%] ">
                    <div className="container mx-auto">
                        <div className="py-2">
                            {children}
                        </div>
                    </div>
                </div>
            </main>
        </div>
        </body>
        </html>
    );
}
